from enum import StrEnum


class ApiErrorCode(StrEnum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_HAS_NO_CREDENTIALS = "USER_HAS_NO_CREDENTIALS"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
