from enum import StrEnum


class ApiErrorCode(StrEnum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_HAS_NO_CREDENTIALS = "USER_HAS_NO_CREDENTIALS"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    OBIS_LOGIN_FAILED = "OBIS_LOGIN_FAILED"
    DAILY_MENU_NOT_FOUND = "DAILY_MENU_NOT_FOUND"
